# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0004_companyaccount_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('companyAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('kode_message', models.CharField(max_length=50, verbose_name='Kode Message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('companyAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyAccount')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='companyForum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_forum.CompanyForum'),
        ),
    ]
