# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=27)),
                ('company_industries', models.CharField(max_length=100)),
                ('company_website', models.TextField()),
                ('company_headquarters', models.CharField(max_length=100)),
                ('company_year_founded', models.CharField(max_length=4)),
                ('company_type', models.CharField(max_length=50)),
                ('company_size', models.CharField(max_length=100)),
                ('company_specialties', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='static/media/images/avatars/', verbose_name='company logo')),
            ],
        ),
    ]
