# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0004_companyaccount_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputForum', models.TextField()),
                ('CompanyAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyAccount')),
            ],
        ),
    ]
